title: PCjs Machines
domain: pcjs.org
tagline: Home of the original IBM PC emulator for browsers.
description: >
  PCjs offers a variety of online machine emulators written in JavaScript. Run DOS, Windows, OS/2 and other vintage PC
  applications in a web browser on your desktop computer, iPhone, or iPad. An assortment of microcomputers, minicomputers, terminals,
  programmable calculators, and arcade machines are available, along with an archive of historical software and documentation.
author: Jeff Parsons
logo: /assets/img/logo-home.png
data_dir: configs
left_brace: "{"
right_brace: "}"
encoding: UTF-8

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - README.md
  - TODO.md
  - "*.log"
  - tmp
  - "**/archive"
  - "**/private"
  - /package*.json
  - /.history
  - /.vscode
  - /diskettes
  - /gamedisks
  - /harddisks
  - /node_modules
  - /software/pcx86/sys/dos/microsoft/1.25/src
  - /software/pcx86/sys/dos/microsoft/2.11/src

github:
  owner_name: "jeffpar"
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/pcjs.org
  pages: https://github.com/jeffpar/pcjs.org/tree/master

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
#   disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

software:
  diskettes:
    server: https://diskettes.pcjs.org
  gamedisks:
    server: https://gamedisks.pcjs.org
  harddisks:
    server: https://harddisks.pcjs.org

archive:
  ms:
    server: https://msarchive.pcjs.org
  kb:
    server: https://jeffpar.github.io/kbarchive
